### ISSUE TITLE
Installation Chunk download failed

### ISSUE THREAD

**Issue by gustavocodigo** [Tempaccnt/Termux-alpaca#2]
after trying to install it on android phone it print the following message:

```
WARNING: chunk download failed (Server returned 509 (over quota)), re-trying after 2 seconds
ggml-alpaca-7b-q4.bin: 38.23% - 1.5 GiB (1610612736 bytes) WARNING: chunk download failed (Server returned 509 (over quota)), re-trying after 4 seconds
```
and keep re-trying. on a Infinite loop.

![Screenshot_20230816-024931_Termux](https://github.com/Tempaccnt/Termux-alpaca/assets/108258194/831cb893-cb50-49bd-bf29-59a30708cd60)

**Comment by Tempaccnt** [comment]
from the error message, it seems that you run out of download quota. I think you chose  Mega to download the model however mega limit your download to 5GB per day. so if you used mega elsewhere you will run out of quota.

anyways, you can use the huggingface face server instead or wait a day before trying Mega again. if this helps let me know.

**Comment by gustavocodigo** [comment]
Yes I switch it to the first download option and solved the issue !

**Comment by Tempaccnt** [comment]
Great, enjoy
